### PR TITLE
OS detection

### PR DESCRIPTION
**Pull request by mpardalos**
Remove the need to source configure.sh to set the OS. I have only tested this on amd64 linux, so I'm not sure the names are right on any other platform.

### CODE REVIEW

**Comment by johnwickerson** [comment]
This PR breaks the Travis-CI build.

**Comment by mpardalos** [comment]
Should be ok now, I removed the running_osx function without removing its uses right before commiting :man_facepalming:

**Comment by johnwickerson** [comment]
Looks good to me!

**Comment by mpardalos** [comment]
Took me a little while to open this up for review :sweat_smile: you should be able to accept this now.

**Comment by johnwickerson** [comment]
Thanks for fixing this, Michalis! Much appreciated.

**Pull request merged**
