### PR TITLE
Mk2 two-event CAS

### PR DESCRIPTION
**Pull request by MattWindsor91**
After offline conversation with @johnwickerson, here is a somewhat different second version of two-event CAS support in `memalloy`'s C generator.

Differences are:
- We go back to emitting two Litmus events for a two-event CAS.  These are named `LoadLink` and `StoreCnd`, since in a RISC assembly witness they would correspond to LL/SC instructions, not a CAS.
- The C pretty-printer now has jurisdiction over deciding when to emit a CAS: always emits an `atomic_compare_exchange_strong_explicit` when it sees a `LoadLink`, and a nop when it sees a `StoreCnd`.
- Some work on making the C pretty-printer suppress erroneous semicolons, which is now useful for `StoreCnd` as well as transactions.

Caveats:
- I haven't tested this with assembly witnesses yet.
- There might be better names for `LoadLink` and `StoreCnd`.
- The `LoadLink` event carries a lot of duplicated information from the `StoreCnd`.  This is so the C emitter can just look at one event when synthesising a CAS; otherwise, it would have to collect both instructions to generate the CAS.  It might be more semantically pleasing, if a lot more complex in the pretty-printer end, to do the latter instead.
- The C pretty-printer doesn't quite handle _not_ emitting code for a basic instruction properly, even with semicolon removal.  Depending on how we handle a newline, it either prints a blank line or a double indent!  To mask this, I've made it emit a comment for `StoreCnd`, but this is just wallpapering over the problem.

### CODE REVIEW

**Comment by johnwickerson** [comment]
Thanks for this Matt. Unfortunately the Travis-CI build failed. I see that the tests `make adding_txns_arm8_4ev_allowset` and `make adding_txns_arm8_3ev` and `make adding_txns_ppc_4ev_allowset` all resulted in `exception Failure("Not yet implemented! r0 := ll(y,0,1,X)")`. Presumably this is a result of your first caveat above about not having tested this on assembly yet?

**Comment by MattWindsor91** [comment]
Ah dangit.  I forgot to check exactly what test invocation Travis was using—`make moretests` didn't catch this.

I'll have a look-see at what I need to do to get this working again.

**Comment by MattWindsor91** [comment]
@johnwickerson should the HW translation of `LoadLink` and `StoreCnd` be the same as the (`X`-tagged `Load`) and `Store`? 

(In fact, should I just get rid of `StoreCnd` and/or `LoadLink` entirely?  I guess it makes some sense for `LoadLink` to be separate, but if needs be I could just move the extra parameters into `option`s.  `StoreCnd` is a bit redundant either way.)

**Comment by johnwickerson** [comment]
Yes, to my mind the `Load` with attribute `"X"` is the same as `LoadLink`; similar for stores.
>In fact, should I just get rid of StoreCnd and/or LoadLink entirely? 

I don't feel strongly either way. Getting rid of one without the other might be a bit weird though. If you do keep `LoadLink` and `StoreCnd`, maybe best to remove the `"X"` attribute altogether, to avoid having multiple representations of the same thing.

**Comment by MattWindsor91** [comment]
Ok, I've tried to fix the above, mostly by replacing the "X" branches in `litmus_HW` with LL/SC ones.

> If you do keep LoadLink and StoreCnd, maybe best to remove the "X" attribute altogether, to avoid having multiple representations of the same thing.

It looks like this wouldn't be too hard to do, except for `mk_Access` in `litmus_HW` which expects to be able to glean exclusivity from attributes.

I definitely don't mind telescoping the LL/SC legs back into their non-exclusive ones if it's cleaner to do so—as a bit of an outsider looking in on the codebase, I'm not sure which'd be better :)

**Comment by johnwickerson** [comment]
Thanks for the PR!

**Pull request merged**
